name: Keycloak FranceConnect Tag

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v2

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Set current version
        run: ./mvnw -B versions:set -DnewVersion=${{ steps.get_version.outputs.VERSION }}

      - name: Build with Maven
        run: ./mvnw -B clean verify

      - name: Upload jar
        uses: actions/upload-artifact@v2
        with:
          name: jar
          path: target/*.jar

  release:
    needs: build
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout artifact
        uses: actions/download-artifact@v2
        with:
          name: jar
          path: target

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.build.outputs.version }}
          release_name: ${{ needs.build.outputs.version }}
          body: |
            ${{github.event.head_commit.message}}
          draft: false
          prerelease: false

      - name: Upload Release javadoc
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/keycloak-franceconnect-${{ needs.build.outputs.version }}-javadoc.jar
          asset_name: keycloak-franceconnect-${{ needs.build.outputs.version }}-javadoc.jar
          asset_content_type: jar

      - name: Upload Release sources
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/keycloak-franceconnect-${{ needs.build.outputs.version }}-sources.jar
          asset_name: keycloak-franceconnect-${{ needs.build.outputs.version }}-sources.jar
          asset_content_type: jar

      - name: Upload Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/keycloak-franceconnect-${{ needs.build.outputs.version }}.jar
          asset_name: keycloak-franceconnect-${{ needs.build.outputs.version }}.jar
          asset_content_type: jar
