name: Keycloak FranceConnect Tag

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v3

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          java-package: 'jdk'

      - id: get_version
        run: echo "VERSION=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_OUTPUT

      - name: Set current version
        run: ./mvnw -B versions:set -DnewVersion=${{ steps.get_version.outputs.VERSION }}

      - name: Build with Maven
        run: ./mvnw -B clean verify

      - name: Upload jar
        uses: actions/upload-artifact@v3
        with:
          name: jar
          path: target/*.jar

  release:
    needs: build
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout artifact
        uses: actions/download-artifact@v3
        with:
          name: jar
          path: target

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.build.outputs.version }}
          name: ${{ needs.build.outputs.version }}
          body: |
            ${{github.event.head_commit.message}}
          draft: false
          prerelease: false
          files: |
            ./target/keycloak-franceconnect-${{ needs.build.outputs.version }}-javadoc.jar
            ./target/keycloak-franceconnect-${{ needs.build.outputs.version }}-sources.jar
            ./target/keycloak-franceconnect-${{ needs.build.outputs.version }}.jar
